# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fac28101fdd8fcd23afae5648e336fc0b36e249e85cd0c99262fbe7b2df52b8c14f6fce7f89f1624f2c94cba5b13d8d86759230b29e04c0c48d97f3f07f974a

test:
  secret_key_base: 0cc1c9c4dc241263e88b247f930ffa43e381a1de6f86fc39e1d1115bd3b80917cb3ab413c2244c553da098421fca4aae25a65d81c5e72e413e2feeec9ef7940c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
